import tkinter as tk
janela = tk. Tk()
janela.title("Primeira Interface")
janela.geometry("800x600")
janela.resizable(True, False)
janela.configure(bg = "lightgreen")
janela.state("zoomed")
label_nome = tk.Label(janela, text="Digite seu nome-pack")
label_nome.pack(pady=2)
entry_nome = tk.Entry(janela)
entry_nome.pack(pady=5)
label_senha = tk.Label(janela, text="Digite sua senha-grid")
label_senha.pack(pady=2)
entry_senha = tk.Entry(janela)
entry_senha.pack(pady=5)
label_curso = tk.Label(janela,text= "Digite seu curso-grid")
label_curso.pack(pady=2)
entry_curso = tk.Entry(janela)
entry_curso.pack(pady=5)
janela.mainloop()
