import tkinter as tk
def mudar():
    if frame1.winfo_viewable():
        frame1.pack_forget()
        frame2.pack(fill="both", expand=True)
    elif frame2.winfo_viewable():
        frame2.pack_forget()
        frame3.pack(fill="both", expand=True)
    elif frame3.winfo_viewable():
          frame3.pack_forget()
          frame4.pack(fill="both", expand=True)
    else:
        frame2.pack(fill="both", expand=True)
        frame1.pack_forget()
        frame3.pack_forget()
        frame4.pack_forget()

janela = tk.Tk()
janela.title("Interface com frames")
janela.geometry("800x500")
janela.state("zoomed")
frame1 = tk.Frame(janela, bg="Green")
label1 = tk.Label(frame1, text= "Tela 1")
label1.pack(pady=5)
button1 = tk.Button(frame1, text="Mudar", command=mudar)
button1.pack(pady=5)
frame2 = tk.Frame(janela, bg="lightblue")
label2 = tk.Label(frame2,text ="Tela2" )
label2.pack(pady=10)
button2 = tk.Button(frame2, text="Mudar", command=mudar)
button2.pack(pady=10)
frame3 = tk.Frame(janela, bg="orange")
label3 = tk.Label(frame3, text="Tela3")
label3.pack(pady=10)
button3 = tk.Button(frame3, text="Mudar", command=mudar)
button3.pack(pady=10)
frame4 = tk.Frame(janela, bg="lightyellow")
label4 = tk.Label(frame4, text="Tela4")
label4.pack(pady=10)
button4 = tk.Button(frame4, text="Mudar", command=mudar)
frame1.pack(fill="both", expand=True)
janela.mainloop()